name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  fuzz:
    name: Batch fuzzing (6 hours)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          fuzz-seconds: 21600
          mode: "batch"
