name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - ".clusterfuzzlite/**"
      - ".github/workflows/cflite_pr.yml"

permissions: {}

jobs:
  fuzz:
    name: PR fuzzing (short run)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          fuzz-seconds: 300
          mode: "code-change"
          output-sarif: true
